### ISSUE TITLE
every tools need a better description

### ISSUE THREAD

**Issue by MAKIO135** [emlyon/makers-academy#4]
On intro.html, there should be a short text explaining what is the makers' toolbox and how prototyping skills can be usefull ( what can be done, as well as intrapreneurship, ... ).
We could as well include links/video of our firsts conferences ( Maker Tour Asia / Constance Garnier / @tart2000 ).

**Comment by AnnaAf** [comment]
Learning how to use these rapid prototyping tools opens a whole set of new opportunities. And the makers' toolbox is the first step of learning how to envision and prototype your ideas. 

This initiation to the makers' lab digital fabrication tools will teach you the basics of lasercutting, 3D printing, Arduino & the web coding. 

**Do not just describe things anymore, make them !** 

Want to learn more about the maker movement ?
Watch the [Maker Tour Asia conference](https://www.youtube.com/watch?v=qAZ6_Q1CRK8&t=1s)

**Comment by MAKIO135** [comment]
As @AnnaAf did for intro, we should introduce with more details every tools presented: what are they used for, add visual exemples and how it can be used in the makers'lab ( open access vs on demand / what kind of material / ... )

**Comment by AnnaAf** [comment]
I take the task. I'll do it in the train this afternoon and push it on Github on Tuesday ;)

**Comment by MAKIO135** [comment]
- [ ] 3dprinting
- [ ] webcoding
- [ ] lasercutting
- [ ] electronics
